source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.0'

#use_frameworks!

abstract_target 'common' do
  pod 'Pitaya', :git => 'https://github.com/taledog/libpitaya.git'
  target 'PitayaClientSwift' do
    pod 'Alamofire', '~> 4.8.1'
  end
  target 'PitayaClientSwiftTests' do
    pod 'Protobuf'
  end
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
      config.build_settings['SWIFT_VERSION'] = '4.2'
    end
  end
end
